### ISSUE TITLE
Further optimize performance for precis-profiles::common::normalization_form_nfkc

### ISSUE THREAD

**Issue by zacknewman** [sancane/precis#39]
[According to the comment](https://github.com/sancane/precis/blob/main/precis-profiles/src/common.rs#L25) for `precis-profiles::common::normalization_form_nfkc`, [`unicode-normalization::is_nfkc`](https://docs.rs/unicode-normalization/latest/unicode_normalization/fn.is_nfkc.html) is called in order to try to "save memory allocations" at the cost of making the function "a bit less efficient due to the extra iteration over the string" when the string is not normalized. `unicode-normalization::is_nfkc` internally might [rely on memory allocations](https://docs.rs/unicode-normalization/latest/unicode_normalization/enum.IsNormalized.html) though. It would be nice if [`unicode-normalization::is_nfkc_quick`](https://docs.rs/unicode-normalization/latest/unicode_normalization/fn.is_nfkc_quick.html) were used instead. A similar argument applies to [`precis-profiles::common::normalization_form_nfc`](https://github.com/sancane/precis/blob/main/precis-profiles/src/common.rs#L36).

I don't have an opinion on what to do in the event [`IsNormalized::Maybe`](https://docs.rs/unicode-normalization/latest/unicode_normalization/enum.IsNormalized.html#variant.Maybe) is returned. Specifically, I don't care if normalization is done then or one uses `unicode-normalization::is_nfkc` to definitively check.

**Comment by sancane** [comment]
IMO, I believe it is justified to accept this slight trade-off in this scenario. The alternative approach may result in false positives or indeterminate results, even if the string to be checked could be perfectly normalized. If, for any reason, we need to support such cases, implementing a flaky "quick" API to compare strings would be a preferable option. This would allow users to make informed choices based on their specific needs in each case.
