### ISSUE TITLE
Re-export `precis-core` in `precis-profiles`

### ISSUE THREAD

**Issue by zacknewman** [sancane/precis#48]
When types or `trait`s of dependencies are part of the public API for a crate, it's common for the dependency itself or at least the used types/`trait`s  in the dependency to be re-exported. There are a lot of resources that go over this, but here is [one](https://lurklurk.org/effective-rust/re-export.html).

Admittedly one of the main reasons for this is to allow downstream code to depend on a different version of the dependency which seems _highly_ unlikely for `precis-core`; however it still does make it ever so slightly more convenient since downstream code won't even need to add a dependency to `precis-core`. `precis-profiles` is essentially useless by itself; so it will almost always be the case that downstream code will need to add a dependency to `precis-core` manually.

Would it be possible to add

```rust
pub use precis_core;
```

to [`precis-profiles`](https://github.com/sancane/precis/blob/main/precis-profiles/src/lib.rs#L34)?

**Comment by sancane** [comment]
I don't see why not, it makes perfect sense.
Please feel free to submit a patch
